@startuml
abstract class "Template`1"<T> {
    + <<override>> Run() : void
    + <<override>> GetNextTemplateId() : string
}
class "Result`1"<T> {
}
BaseTemplate <|-- "Template`1"
"Template`1" --> "Result<T>" "Result`1"
@enduml
